### ISSUE TITLE
[DELETED]

### ISSUE THREAD

**Issue by daibanshixianglan** [rootkiter/Termite#2]
-

**Comment by rootkiter** [comment]
都是windows
版本的么

Hello World

**Comment by rootkiter** [comment]
嗯，昨天也有人说windows里的会问题，抽空我研究研究。
在新版本的win上，它一些api对posix标准支持不好。应该是某个基础API实现上做了改动。

如果方便的话，请把各个运行环境的系统号留在这里，我有时间的时候研究下。

Hello World

**Comment by jglimmers** [comment]
环境1：admin（win7 6.1.7601 Service Pack 1 Build 7601）agent_public（xp 5.1.2600 Service Pack 3 Build 2600） agent（server 08 r2）
环境2：admin（win server 12 r2）agent_public（server 12 r2） agent（server 08 r2）

**Comment by rootkiter** [comment]
收到

Hello World

**Comment by rootkiter** [comment]
如果方便的话，可以帮测下新版本是否还存在这个问题。。
PS: 无回复的话，我会在两天后关闭这个Issues，如仍然存在类似问题可开新 Issues 讨论。

**Comment by daibanshixianglan** [comment]
Hi, 能不能删掉这条issue，谢谢~
